package com.aurainsani.hgg;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.text.InputType;import android.view.*;import android.widget.*;
import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.text.*;import java.util.*;import java.util.concurrent.*;

public class MainActivity extends Activity {
    static final String API="https://pengobatan.aurainsani.com/wp-json/hgg/v1/";
    SharedPreferences sp; LinearLayout root; ExecutorService exec=Executors.newSingleThreadExecutor(); JSONObject me;
    int pad=20;
    @Override public void onCreate(Bundle b){super.onCreate(b); sp=getSharedPreferences("hgg",0); showStart();}
    TextView tv(String s,int size){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(Color.rgb(15,23,42));v.setPadding(0,6,0,6);return v;}
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}
    EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setPadding(14,10,14,10);e.setSingleLine(true);return e;}
    void base(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(pad,pad,pad,pad);root.setBackgroundColor(Color.rgb(248,250,252));ScrollView sv=new ScrollView(this);sv.addView(root);setContentView(sv); TextView h=tv(title,25);h.setTypeface(null,1);root.addView(h);}
    void showStart(){if(sp.getString("token","").isEmpty()) showLogin(); else loadMe();}
    void showLogin(){base("Aura Insani"); ImageView logo=new ImageView(this);logo.setImageResource(com.aurainsani.hgg.R.drawable.logo_aura_insani);logo.setAdjustViewBounds(true);root.addView(logo,new LinearLayout.LayoutParams(-1,180));root.addView(tv("Konsultasi & Pengobatan H. Galih Gumelar",17));
      EditText wa=input("Nomor WhatsApp");wa.setInputType(InputType.TYPE_CLASS_PHONE);root.addView(wa);EditText pw=input("Password");pw.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);root.addView(pw);Button b=btn("Login Pasien");root.addView(b);b.setOnClickListener(v->login(wa.getText().toString(),pw.getText().toString()));Button r=btn("Daftar pasien baru");root.addView(r);r.setOnClickListener(v->showRegister());}
    void showRegister(){base("Daftar Pasien");EditText n=input("Nama lengkap *"),w=input("Nomor WhatsApp *"),e=input("Email"),u=input("Usia"),p=input("Password *"),p2=input("Ulangi password *");w.setInputType(InputType.TYPE_CLASS_PHONE);u.setInputType(InputType.TYPE_CLASS_NUMBER);p.setInputType(129);p2.setInputType(129);for(EditText x:new EditText[]{n,w,e,u,p,p2})root.addView(x);CheckBox c=new CheckBox(this);c.setText("Saya menyetujui penggunaan data untuk administrasi dan penjadwalan.");root.addView(c);Button b=btn("Buat akun");root.addView(b);b.setOnClickListener(v->register(n.getText().toString(),w.getText().toString(),e.getText().toString(),u.getText().toString(),p.getText().toString(),p2.getText().toString(),c.isChecked()));Button back=btn("Kembali ke login");root.addView(back);back.setOnClickListener(v->showLogin());}
    void home(JSONObject m){me=m;boolean admin=m.optBoolean("is_admin",false);base("Halo, "+m.optString("nama","Pasien")+" 👋");root.addView(tv("ID Pasien: "+m.optString("patient_code")+"\nWhatsApp: "+m.optString("whatsapp"),15));Button book=btn("+ Booking Konsultasi");root.addView(book);book.setOnClickListener(v->showBooking());Button hist=btn("Riwayat Booking");root.addView(hist);hist.setOnClickListener(v->loadBookings());if(admin){Button ad=btn("Dashboard Admin");root.addView(ad);ad.setOnClickListener(v->loadAdmin());}Button wa=btn("WhatsApp Admin");root.addView(wa);wa.setOnClickListener(v->openWA());Button out=btn("Logout");root.addView(out);out.setOnClickListener(v->logout());}
    void loadMe(){api("GET","me",null,(o)->home(o.getJSONObject("user")));}
    void login(String wa,String pw){if(wa.isEmpty()||pw.isEmpty()){toast("Nomor WhatsApp dan password wajib diisi");return;}JSONObject j=new JSONObject();try{j.put("whatsapp",wa);j.put("password",pw);}catch(Exception ignored){}api("POST","auth/login",j,(o)->{sp.edit().putString("token",o.getString("token")).apply();home(o.getJSONObject("user"));});}
    void register(String n,String w,String e,String u,String p,String p2,boolean c){if(n.isEmpty()||w.isEmpty()||p.length()<6||!p.equals(p2)||!c){toast("Lengkapi data dan pastikan password sama");return;}JSONObject j=new JSONObject();try{j.put("nama",n);j.put("whatsapp",w);j.put("email",e);j.put("usia",u);j.put("password",p);j.put("consent",c);}catch(Exception ignored){}api("POST","auth/register",j,(o)->{sp.edit().putString("token",o.getString("token")).apply();home(o.getJSONObject("user"));});}
    void showBooking(){base("Booking Konsultasi");root.addView(tv("Pilih tanggal, jam dan layanan.",15));Button date=btn("Pilih tanggal");root.addView(date);final String[] ds={new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date())};TextView picked=tv(ds[0],15);root.addView(picked);Spinner service=new Spinner(this);String[] sv={"Pilih layanan","Konsultasi","Konsultasi Lanjutan","Konsultasi Online","Informasi Layanan"};service.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,sv));root.addView(service);LinearLayout slots=new LinearLayout(this);slots.setOrientation(LinearLayout.VERTICAL);root.addView(slots);EditText kel=input("Keluhan / catatan singkat");kel.setSingleLine(false);kel.setMinLines(4);root.addView(kel);Button save=btn("Konfirmasi Booking");root.addView(save);date.setOnClickListener(v->{Calendar c=Calendar.getInstance();DatePickerDialog d=new DatePickerDialog(this,(x,y,m,day)->{ds[0]=String.format(Locale.US,"%04d-%02d-%02d",y,m+1,day);picked.setText(ds[0]);loadSlots(ds[0],slots,save);},c.get(1),c.get(2),c.get(5));d.show();});save.setOnClickListener(v->{String layanan=service.getSelectedItem().toString();String jam=(String)save.getTag();if(layanan.startsWith("Pilih")||jam==null){toast("Pilih layanan dan jam");return;}JSONObject j=new JSONObject();try{j.put("tanggal",ds[0]);j.put("jam",jam);j.put("layanan",layanan);j.put("keluhan",kel.getText().toString());}catch(Exception ignored){}api("POST","bookings",j,(o)->{toast("Booking berhasil: "+o.getJSONObject("booking").optString("kode_booking"));home(me);});});loadSlots(ds[0],slots,save);}
    void loadSlots(String d){loadSlots(d,null,null);}void loadSlots(String d,LinearLayout box,Button save){if(box==null)return;api("GET","slots?date="+d,null,(o)->{box.removeAllViews();JSONArray a=o.getJSONArray("slots");for(int i=0;i<a.length();i++){JSONObject x=a.getJSONObject(i);Button b=btn(x.getString("jam")+(x.getBoolean("tersedia")?"":" (penuh)"));b.setEnabled(x.getBoolean("tersedia"));box.addView(b);b.setOnClickListener(v->{save.setTag(x.optString("jam"));toast("Jam dipilih: "+x.optString("jam"));});}});}
    void loadBookings(){api("GET","bookings",null,(o)->{base("Riwayat Booking");JSONArray a=o.getJSONArray("items");if(a.length()==0)root.addView(tv("Belum ada riwayat booking.",16));for(int i=0;i<a.length();i++){JSONObject x=a.getJSONObject(i);TextView t=tv(x.optString("kode_booking")+"\n"+x.optString("tanggal")+" • "+x.optString("jam")+"\n"+x.optString("layanan")+"\nStatus: "+x.optString("status"),15);t.setPadding(12,14,12,14);root.addView(t);}Button b=btn("Kembali");root.addView(b);b.setOnClickListener(v->home(me));});}
    void loadAdmin(){api("GET","admin/stats",null,(o)->{base("Dashboard Admin");JSONObject s=o.getJSONObject("stats");root.addView(tv("Hari ini: "+s.optInt("today")+"\nMenunggu: "+s.optInt("waiting")+"\nDikonfirmasi: "+s.optInt("confirmed")+"\nSelesai: "+s.optInt("done"),18));JSONArray a=o.getJSONArray("items");for(int i=0;i<a.length();i++){JSONObject x=a.getJSONObject(i);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.setPadding(8,8,8,8);row.addView(tv(x.optString("kode_booking")+" • "+x.optString("nama")+"\n"+x.optString("tanggal")+" "+x.optString("jam")+" • "+x.optString("layanan"),14));Spinner st=new Spinner(this);String[] ss={"Menunggu","Dikonfirmasi","Selesai","Dibatalkan"};st.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,ss));row.addView(st);Button up=btn("Update status");row.addView(up);final int id=x.optInt("id");up.setOnClickListener(v->{JSONObject j=new JSONObject();try{j.put("status",st.getSelectedItem().toString());}catch(Exception ignored){}api("PATCH","admin/bookings/"+id,j,z->toast("Status diperbarui"));});root.addView(row);}Button b=btn("Kembali");root.addView(b);b.setOnClickListener(v->home(me));});}
    void openWA(){String wa="6288973651329";try{startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse("https://wa.me/"+wa)));}catch(Exception e){toast("WhatsApp tidak tersedia");}}
    void logout(){api("POST","auth/logout",null,o->{sp.edit().clear().apply();showLogin();});}
    interface CB{void ok(JSONObject o)throws Exception;}
    void api(String method,String path,JSONObject body,CB cb){progress(true);exec.execute(()->{try{URL u=new URL(API+path);HttpURLConnection c=(HttpURLConnection)u.openConnection();c.setRequestMethod(method);c.setConnectTimeout(15000);c.setReadTimeout(20000);c.setRequestProperty("Accept","application/json");String token=sp.getString("token","");if(!token.isEmpty())c.setRequestProperty("Authorization","Bearer "+token);if(body!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=UTF-8");try(OutputStream os=c.getOutputStream()){os.write(body.toString().getBytes(StandardCharsets.UTF_8));}}int code=c.getResponseCode();InputStream is=code>=400?c.getErrorStream():c.getInputStream();String res=read(is);JSONObject o=new JSONObject(res);if(code>=400)throw new Exception(o.optString("message","Permintaan gagal"));runOnUiThread(()->{progress(false);try{cb.ok(o);}catch(Exception e){toast(e.getMessage());}});}catch(Exception e){runOnUiThread(()->{progress(false);toast(e.getMessage()==null?"Koneksi gagal":e.getMessage());});}});}
    String read(InputStream in)throws Exception{if(in==null)return "{}";BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder b=new StringBuilder();String l;while((l=r.readLine())!=null)b.append(l);return b.toString();}
    void progress(boolean on){if(on){Toast.makeText(this,"Memproses...",Toast.LENGTH_SHORT).show();}}
    void toast(String s){runOnUiThread(()->Toast.makeText(this,s,Toast.LENGTH_LONG).show());}
    @Override protected void onDestroy(){exec.shutdownNow();super.onDestroy();}
}
