package com.aurainsani.hgg;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.text.InputType;import android.view.*;import android.widget.*;
import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.text.*;import java.util.*;import java.util.concurrent.*;

public class MainActivity extends Activity {
    static final String API="https://pengobatan.aurainsani.com/wp-json/hgg/v1/";
    SharedPreferences sp; LinearLayout root; ExecutorService exec=Executors.newSingleThreadExecutor(); JSONObject me; int pad=20;
    @Override public void onCreate(Bundle b){super.onCreate(b);sp=getSharedPreferences("hgg",0);showStart();}
    TextView tv(String s,int size){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(Color.rgb(15,23,42));v.setPadding(0,6,0,6);return v;}
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}
    EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setPadding(14,10,14,10);e.setSingleLine(true);return e;}
    void base(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(pad,pad,pad,pad);root.setBackgroundColor(Color.rgb(248,250,252));ScrollView sv=new ScrollView(this);sv.addView(root);setContentView(sv);TextView h=tv(title,25);h.setTypeface(null,1);root.addView(h);}
    void showStart(){if(sp.getString("token","").isEmpty())showLogin();else loadMe();}
    void showLogin(){base("Aura Insani");ImageView logo=new ImageView(this);logo.setImageResource(com.aurainsani.hgg.R.drawable.logo_aura_insani);logo.setAdjustViewBounds(true);root.addView(logo,new LinearLayout.LayoutParams(-1,180));root.addView(tv("Konsultasi & Pengobatan H. Galih Gumelar",17));EditText wa=input("Nomor WhatsApp");wa.setInputType(InputType.TYPE_CLASS_PHONE);root.addView(wa);EditText pw=input("Password");pw.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);root.addView(pw);Button b=btn("Login Pasien");root.addView(b);b.setOnClickListener(v->login(wa.getText().toString(),pw.getText().toString()));Button r=btn("Daftar pasien baru");root.addView(r);r.setOnClickListener(v->showRegister());}
    void showRegister(){base("Daftar Pasien");EditText n=input("Nama lengkap *"),w=input("Nomor WhatsApp *"),e=input("Email"),u=input("Usia"),p=input("Password *"),p2=input("Ulangi password *");w.setInputType(InputType.TYPE_CLASS_PHONE);u.setInputType(InputType.TYPE_CLASS_NUMBER);p.setInputType(129);p2.setInputType(129);for(EditText x:new EditText[]{n,w,e,u,p,p2})root.addView(x);CheckBox c=new CheckBox(this);c.setText("Saya menyetujui penggunaan data untuk administrasi dan penjadwalan.");root.addView(c);Button b=btn("Buat akun");root.addView(b);b.setOnClickListener(v->register(n.getText().toString(),w.getText().toString(),e.getText().toString(),u.getText().toString(),p.getText().toString(),p2.getText().toString(),c.isChecked()));Button back=btn("Kembali ke login");root.addView(back);back.setOnClickListener(v->showLogin());}
    JSONObject data(JSONObject o){JSONObject d=o.optJSONObject("data");return d!=null?d:o.optJSONObject("user")!=null?o.optJSONObject("user"):o;}
    void home(JSONObject m){me=m;base("Halo, "+m.optString("nama",m.optString("name","Pasien"))+" 👋");root.addView(tv("ID Pasien: "+m.optString("patient_code",m.optString("id_pasien","-"))+"\nWhatsApp: "+m.optString("whatsapp","-"),15));Button book=btn("+ Booking Konsultasi");root.addView(book);book.setOnClickListener(v->showBooking());Button hist=btn("Riwayat Booking");root.addView(hist);hist.setOnClickListener(v->loadBookings());Button wa=btn("WhatsApp Admin");root.addView(wa);wa.setOnClickListener(v->openWA());Button out=btn("Logout");root.addView(out);out.setOnClickListener(v->logout());}
    void loadMe(){api("GET","me",null,o->home(data(o)));}
    void login(String wa,String pw){if(wa.isEmpty()||pw.isEmpty()){toast("Nomor WhatsApp dan password wajib diisi");return;}JSONObject j=new JSONObject();try{j.put("whatsapp",wa);j.put("password",pw);}catch(Exception ignored){}apiWithFallback("POST",new String[]{"login","signin","patient/login","patients/login"},j,o->{String token=tokenOf(o);if(token.isEmpty())throw new Exception("Login berhasil tetapi sesi tidak diterima. Silakan coba lagi.");sp.edit().putString("token",token).apply();home(data(o));});}
    void register(String n,String w,String e,String u,String p,String p2,boolean c){if(n.isEmpty()||w.isEmpty()||p.length()<6||!p.equals(p2)||!c){toast("Lengkapi data dan pastikan password sama");return;}JSONObject j=new JSONObject();try{j.put("nama",n);j.put("whatsapp",w);j.put("email",e);j.put("usia",u);j.put("password",p);j.put("password2",p2);j.put("consent",c);}catch(Exception ignored){}apiWithFallback("POST",new String[]{"signup","register","patient/register","patients/register"},j,o->{String token=tokenOf(o);if(token.isEmpty())throw new Exception("Pendaftaran berhasil tetapi sesi login tidak diterima. Silakan login dengan nomor WhatsApp dan password yang baru dibuat.");sp.edit().putString("token",token).apply();home(data(o));});}
    void showBooking(){base("Booking Konsultasi");root.addView(tv("Pilih tanggal, jam dan layanan.",15));Button date=btn("Pilih tanggal");root.addView(date);final String[] ds={new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date())};TextView picked=tv(ds[0],15);root.addView(picked);Spinner service=new Spinner(this);String[] sv={"Pilih layanan","Konsultasi","Konsultasi Lanjutan","Konsultasi Online","Informasi Layanan"};service.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,sv));root.addView(service);LinearLayout slots=new LinearLayout(this);slots.setOrientation(LinearLayout.VERTICAL);root.addView(slots);EditText kel=input("Keluhan / catatan singkat");kel.setSingleLine(false);kel.setMinLines(4);root.addView(kel);Button save=btn("Konfirmasi Booking");root.addView(save);date.setOnClickListener(v->{Calendar c=Calendar.getInstance();DatePickerDialog d=new DatePickerDialog(this,(x,y,m,day)->{ds[0]=String.format(Locale.US,"%04d-%02d-%02d",y,m+1,day);picked.setText(ds[0]);loadSlots(ds[0],slots,save);},c.get(1),c.get(2),c.get(5));d.show();});save.setOnClickListener(v->{String layanan=service.getSelectedItem().toString();String jam=(String)save.getTag();if(layanan.startsWith("Pilih")||jam==null){toast("Pilih layanan dan jam");return;}JSONObject j=new JSONObject();try{j.put("tanggal",ds[0]);j.put("jam",jam);j.put("layanan",layanan);j.put("keluhan",kel.getText().toString());}catch(Exception ignored){}api("POST","booking",j,o->{JSONObject d=data(o);toast("Booking berhasil: "+d.optString("kode_booking",d.optString("booking_code","-")));home(me);});});loadSlots(ds[0],slots,save);}
    void loadSlots(String d){loadSlots(d,null,null);}void loadSlots(String d,LinearLayout box,Button save){if(box==null)return;api("GET","slots",null,o->{box.removeAllViews();JSONArray a=o.optJSONArray("data");if(a==null)a=o.optJSONArray("slots");if(a==null||a.length()==0){box.addView(tv("Belum ada slot aktif.",14));return;}for(int i=0;i<a.length();i++){JSONObject x=a.getJSONObject(i);String jam=x.optString("jam",x.optString("time",""));boolean aktif=x.optBoolean("aktif",true);Button b=btn(jam+(aktif?"":" (penuh)"));b.setEnabled(aktif);box.addView(b);b.setOnClickListener(v->{save.setTag(jam);toast("Jam dipilih: "+jam);});}});}
    void loadBookings(){api("GET","me",null,o->{JSONObject d=data(o);base("Riwayat Booking");JSONArray a=d.optJSONArray("riwayat_booking");if(a==null)a=d.optJSONArray("bookings");if(a==null)a=new JSONArray();if(a.length()==0)root.addView(tv("Belum ada riwayat booking.",16));for(int i=0;i<a.length();i++){JSONObject x=a.getJSONObject(i);TextView t=tv(x.optString("kode_booking",x.optString("booking_code","-"))+"\n"+x.optString("tanggal")+" • "+x.optString("jam")+"\n"+x.optString("layanan")+"\nStatus: "+x.optString("status"),15);t.setPadding(12,14,12,14);root.addView(t);}Button b=btn("Kembali");root.addView(b);b.setOnClickListener(v->home(me));});}
    void openWA(){String wa="6288973651329";try{startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse("https://wa.me/"+wa)));}catch(Exception e){toast("WhatsApp tidak tersedia");}}
    void logout(){api("POST","logout",null,o->{sp.edit().clear().apply();showLogin();});}
    interface CB{void ok(JSONObject o)throws Exception;}
    String tokenOf(JSONObject o){String t=o.optString("token",o.optString("access_token",""));if(t.isEmpty()){JSONObject d=o.optJSONObject("data");if(d!=null)t=d.optString("token",d.optString("access_token",""));}return t;}
    void apiWithFallback(String method,String[] paths,JSONObject body,CB cb){apiAttempt(method,paths,0,body,cb);}
    void apiAttempt(String method,String[] paths,int idx,JSONObject body,CB cb){if(idx>=paths.length){toast("Server API tidak menyediakan endpoint yang dibutuhkan.");return;}progress(true);exec.execute(()->{HttpURLConnection c=null;try{URL u=new URL(API+paths[idx]);c=(HttpURLConnection)u.openConnection();c.setRequestMethod(method);c.setConnectTimeout(15000);c.setReadTimeout(20000);c.setRequestProperty("Accept","application/json");String token=sp.getString("token","");if(!token.isEmpty())c.setRequestProperty("Authorization","Bearer "+token);if(body!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=UTF-8");try(OutputStream os=c.getOutputStream()){os.write(body.toString().getBytes(StandardCharsets.UTF_8));}}int code=c.getResponseCode();InputStream is=code>=400?c.getErrorStream():c.getInputStream();String res=read(is);JSONObject o=new JSONObject(res);if(code==404&&idx+1<paths.length){if(c!=null)c.disconnect();apiAttempt(method,paths,idx+1,body,cb);return;}if(code>=400)throw new Exception(errorMessage(o,code));runOnUiThread(()->{progress(false);try{cb.ok(o);}catch(Exception e){toast(e.getMessage()==null?"Terjadi kesalahan":e.getMessage());}});}catch(Exception e){runOnUiThread(()->{progress(false);toast(e.getMessage()==null?"Koneksi ke server gagal":e.getMessage());});}finally{if(c!=null)c.disconnect();}});}
    String errorMessage(JSONObject o,int code){String m=o.optString("message","");if(m.isEmpty()){JSONObject d=o.optJSONObject("data");if(d!=null)m=d.optString("message","");}if(m.isEmpty())m=o.optString("code","");if(m.equals("rest_no_route")||m.toLowerCase(Locale.US).contains("tidak ada rute"))return "Endpoint aplikasi belum tersedia di server (HTTP "+code+").";return m.isEmpty()?"Permintaan gagal (HTTP "+code+")":m;}
    void api(String method,String path,JSONObject body,CB cb){progress(true);exec.execute(()->{HttpURLConnection c=null;try{URL u=new URL(API+path);c=(HttpURLConnection)u.openConnection();c.setRequestMethod(method);c.setConnectTimeout(15000);c.setReadTimeout(20000);c.setRequestProperty("Accept","application/json");String token=sp.getString("token","");if(!token.isEmpty())c.setRequestProperty("Authorization","Bearer "+token);if(body!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=UTF-8");try(OutputStream os=c.getOutputStream()){os.write(body.toString().getBytes(StandardCharsets.UTF_8));}}int code=c.getResponseCode();InputStream is=code>=400?c.getErrorStream():c.getInputStream();String res=read(is);JSONObject o=new JSONObject(res);if(code==401&&path.equals("me")){sp.edit().remove("token").apply();runOnUiThread(()->{progress(false);toast("Sesi berakhir. Silakan login kembali.");showLogin();});return;}if(code>=400)throw new Exception(errorMessage(o,code));runOnUiThread(()->{progress(false);try{cb.ok(o);}catch(Exception e){toast(e.getMessage()==null?"Terjadi kesalahan":e.getMessage());}});}catch(Exception e){runOnUiThread(()->{progress(false);toast(e.getMessage()==null?"Koneksi ke server gagal":e.getMessage());});}finally{if(c!=null)c.disconnect();}});}
    String read(InputStream in)throws Exception{if(in==null)return "{}";BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder b=new StringBuilder();String l;while((l=r.readLine())!=null)b.append(l);return b.toString();}
    void progress(boolean on){if(on)Toast.makeText(this,"Memproses...",Toast.LENGTH_SHORT).show();}
    void toast(String s){runOnUiThread(()->Toast.makeText(this,s,Toast.LENGTH_LONG).show());}
    @Override protected void onDestroy(){exec.shutdownNow();super.onDestroy();}
}
